[package]
name = "rusty_notes"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = "0.4.38"
clap = { version = "4", features = ["derive"] }
crossterm = "0.29.0"
dirs = "6"
ratatui = "0.30.0"
rusqlite = { version = "0.39", features = ["bundled", "chrono"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
notify-rust = "4"
